### ISSUE TITLE
Cannot send anonymous types

### ISSUE THREAD

**Issue by developervariety** [Icemantheditor/NotLiteCode#3]
I'm using the provided serializer and trying to send something like this over,

```csharp
new {
 name = "NoteLiteCode"
} 
```

The client never receives the data

**Comment by ImVexed** [comment]
Hmm, I'd have to look and see if it's possible with Grobuf, but certainly with the standard library `BinaryFormatter` this will raise a serialization exception because the anonymous type isn't marked as serializable.

**Comment by developervariety** [comment]
I would make a class, but I am trying to build the request body on the remote server w/o having the client knowing it. This would stop the possibility of RE'ing the application w/o a valid license to the server.
